### ISSUE TITLE
Documents Paragraph Type should support document titles to prevent filenames being used as links

### ISSUE THREAD

**Issue by danchamp** [localgovdrupal/localgov_subsites#45] opened 2021-06-24 09:22 UTC
There's no provision for documents to have titles defined, so filenames have to be used for the documents list:

<img width="924" alt="Screenshot 2021-06-24 at 10 20 35" src="https://user-images.githubusercontent.com/261421/123237850-ed57aa00-d4d5-11eb-817b-44381e1b9150.png">

This is poor for accessibility and general user experience. Can we allow (require) titles to be defined for when a document is added?

**Comment by keelanfh** [comment] 2023-06-30 15:42
Closed as duplicate of https://github.com/localgovdrupal/localgov_core/issues/47

**Closed as not planned by keelanfh** 2023-06-30 15:42 UTC
